#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Author        : singlepig
# Email         : gys.nanjing@gmail.com
# Description   : get ss password, rely on https://github.com/emamirazavi/python3-ping/blob/master/ping.py


def getNamaho():
    # ssUrl = "http://www.ishadowsocks.net/"
    # namaho = "https://www.namaho.com/prpr.html"
    namahoPasswd = "https://www.namaho.com/passwd"
    headers = {
        "Host": "www.namaho.com",
        "Referer": "https://www.namaho.com/prpr.html",
    }
    ports = [
        8497,
        8498,
        8499
    ]
    req = requests.get(namahoPasswd, headers=headers)
    passwd = req.text.split("\n")
    for (port, pd) in zip(ports, passwd):
        print(port, pd)


def getss():
    ssServers = [
        "jp01.namaho.com",
        "us02.namaho.com",
        "US1.ISS.TF",
        "HK2.ISS.TF",
        "JP3.ISS.TF"
    ]
    pingResult = list(map(pingWrap, ssServers))
    index = pingResult.index(min(pingResult))
    if index < 2:
        # use namaho ss server
        print("{server} is the fastest, {latency}ms".format(server=ssServers[index], latency=int(pingResult[index])))
        getNamaho()
    else:
        # use ishadowsocks ss server
        pass


def pingWrap(server):
    (maxTime, minTime, avrgTime, fracLoss) = ping.quiet_ping(server, timeout=10000, count=4, packet_size=64)
    return avrgTime

if __name__ == '__main__':
    import requests
    import ping
    getss()
    # getNamaho()
